[project]
name = "gpt-from-scratch"
version = "0.1.0"
description = "Hi"
readme = "README.md"
requires-python = "==3.12.11"
dependencies = [
    "numpy==2.3.3",
    "ruff>=0.14.4",
    "torch==2.8.0",
]
